// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_fdxyft0nTDIYrYyQDb8AtM45XU-PjZ0',
    appId: '1:323489419466:android:c73ace8424896c722d2433',
    messagingSenderId: '323489419466',
    projectId: 'picture-note-d07c3',
    storageBucket: 'picture-note-d07c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC1YqCjayLz4GD9PPvD1Sxs7vgt9uhCTg',
    appId: '1:323489419466:ios:79b4a6132edc42e62d2433',
    messagingSenderId: '323489419466',
    projectId: 'picture-note-d07c3',
    storageBucket: 'picture-note-d07c3.appspot.com',
    iosClientId: '323489419466-r35ld97afp5e666ohak4a849maqo55kh.apps.googleusercontent.com',
    iosBundleId: 'com.example.picture-note',
  );
}